package androidx.compose.p002ui.graphics.vector.compat;

/* renamed from: androidx.compose.ui.graphics.vector.compat.AndroidVectorResources */
/* compiled from: AndroidVectorResources.android.kt */
public final class AndroidVectorResources {
    public static final AndroidVectorResources INSTANCE = new AndroidVectorResources();
    private static final int STYLEABLE_VECTOR_DRAWABLE_ALPHA = 4;
    private static final int STYLEABLE_VECTOR_DRAWABLE_AUTO_MIRRORED = 5;
    private static final int[] STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH = {16842755, 16843781};
    private static final int STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH_NAME = 0;
    private static final int STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH_PATH_DATA = 1;
    private static final int[] STYLEABLE_VECTOR_DRAWABLE_GROUP = {16842755, 16843189, 16843190, 16843556, 16843557, 16843558, 16843866, 16843867};
    private static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_NAME = 0;
    private static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_PIVOT_X = 1;
    private static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_PIVOT_Y = 2;
    private static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_ROTATION = 5;
    private static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_SCALE_X = 3;
    private static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_SCALE_Y = 4;
    private static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_TRANSLATE_X = 6;
    private static final int STYLEABLE_VECTOR_DRAWABLE_GROUP_TRANSLATE_Y = 7;
    private static final int STYLEABLE_VECTOR_DRAWABLE_HEIGHT = 2;
    private static final int STYLEABLE_VECTOR_DRAWABLE_NAME = 0;
    private static final int[] STYLEABLE_VECTOR_DRAWABLE_PATH = {16842755, 16843780, 16843781, 16843782, 16843783, 16843784, 16843785, 16843786, 16843787, 16843788, 16843789, 16843979, 16843980, 16844062};
    private static final int STYLEABLE_VECTOR_DRAWABLE_PATH_FILL_ALPHA = 12;
    private static final int STYLEABLE_VECTOR_DRAWABLE_PATH_FILL_COLOR = 1;
    private static final int STYLEABLE_VECTOR_DRAWABLE_PATH_NAME = 0;
    private static final int STYLEABLE_VECTOR_DRAWABLE_PATH_PATH_DATA = 2;
    private static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_ALPHA = 11;
    private static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_COLOR = 3;
    private static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_LINE_CAP = 8;
    private static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_LINE_JOIN = 9;
    private static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_MITER_LIMIT = 10;
    private static final int STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_WIDTH = 4;
    private static final int STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_END = 6;
    private static final int STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_FILLTYPE = 13;
    private static final int STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_OFFSET = 7;
    private static final int STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_START = 5;
    private static final int STYLEABLE_VECTOR_DRAWABLE_TINT = 1;
    private static final int STYLEABLE_VECTOR_DRAWABLE_TINT_MODE = 6;
    private static final int[] STYLEABLE_VECTOR_DRAWABLE_TYPE_ARRAY = {16842755, 16843041, 16843093, 16843097, 16843551, 16843754, 16843771, 16843778, 16843779};
    private static final int STYLEABLE_VECTOR_DRAWABLE_VIEWPORT_HEIGHT = 8;
    private static final int STYLEABLE_VECTOR_DRAWABLE_VIEWPORT_WIDTH = 7;
    private static final int STYLEABLE_VECTOR_DRAWABLE_WIDTH = 3;

    private AndroidVectorResources() {
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_ALPHA() {
        return STYLEABLE_VECTOR_DRAWABLE_ALPHA;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_AUTO_MIRRORED() {
        return STYLEABLE_VECTOR_DRAWABLE_AUTO_MIRRORED;
    }

    public final int[] getSTYLEABLE_VECTOR_DRAWABLE_CLIP_PATH() {
        return STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_CLIP_PATH_NAME() {
        return STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH_NAME;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_CLIP_PATH_PATH_DATA() {
        return STYLEABLE_VECTOR_DRAWABLE_CLIP_PATH_PATH_DATA;
    }

    public final int[] getSTYLEABLE_VECTOR_DRAWABLE_GROUP() {
        return STYLEABLE_VECTOR_DRAWABLE_GROUP;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_GROUP_NAME() {
        return STYLEABLE_VECTOR_DRAWABLE_GROUP_NAME;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_GROUP_PIVOT_X() {
        return STYLEABLE_VECTOR_DRAWABLE_GROUP_PIVOT_X;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_GROUP_PIVOT_Y() {
        return STYLEABLE_VECTOR_DRAWABLE_GROUP_PIVOT_Y;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_GROUP_ROTATION() {
        return STYLEABLE_VECTOR_DRAWABLE_GROUP_ROTATION;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_GROUP_SCALE_X() {
        return STYLEABLE_VECTOR_DRAWABLE_GROUP_SCALE_X;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_GROUP_SCALE_Y() {
        return STYLEABLE_VECTOR_DRAWABLE_GROUP_SCALE_Y;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_GROUP_TRANSLATE_X() {
        return STYLEABLE_VECTOR_DRAWABLE_GROUP_TRANSLATE_X;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_GROUP_TRANSLATE_Y() {
        return STYLEABLE_VECTOR_DRAWABLE_GROUP_TRANSLATE_Y;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_HEIGHT() {
        return STYLEABLE_VECTOR_DRAWABLE_HEIGHT;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_NAME() {
        return STYLEABLE_VECTOR_DRAWABLE_NAME;
    }

    public final int[] getSTYLEABLE_VECTOR_DRAWABLE_PATH() {
        return STYLEABLE_VECTOR_DRAWABLE_PATH;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_PATH_FILL_ALPHA() {
        return STYLEABLE_VECTOR_DRAWABLE_PATH_FILL_ALPHA;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_PATH_FILL_COLOR() {
        return STYLEABLE_VECTOR_DRAWABLE_PATH_FILL_COLOR;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_PATH_NAME() {
        return STYLEABLE_VECTOR_DRAWABLE_PATH_NAME;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_PATH_PATH_DATA() {
        return STYLEABLE_VECTOR_DRAWABLE_PATH_PATH_DATA;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_ALPHA() {
        return STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_ALPHA;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_COLOR() {
        return STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_COLOR;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_LINE_CAP() {
        return STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_LINE_CAP;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_LINE_JOIN() {
        return STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_LINE_JOIN;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_MITER_LIMIT() {
        return STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_MITER_LIMIT;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_WIDTH() {
        return STYLEABLE_VECTOR_DRAWABLE_PATH_STROKE_WIDTH;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_END() {
        return STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_END;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_FILLTYPE() {
        return STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_FILLTYPE;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_OFFSET() {
        return STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_OFFSET;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_START() {
        return STYLEABLE_VECTOR_DRAWABLE_PATH_TRIM_PATH_START;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_TINT() {
        return STYLEABLE_VECTOR_DRAWABLE_TINT;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_TINT_MODE() {
        return STYLEABLE_VECTOR_DRAWABLE_TINT_MODE;
    }

    public final int[] getSTYLEABLE_VECTOR_DRAWABLE_TYPE_ARRAY() {
        return STYLEABLE_VECTOR_DRAWABLE_TYPE_ARRAY;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_VIEWPORT_HEIGHT() {
        return STYLEABLE_VECTOR_DRAWABLE_VIEWPORT_HEIGHT;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_VIEWPORT_WIDTH() {
        return STYLEABLE_VECTOR_DRAWABLE_VIEWPORT_WIDTH;
    }

    public final int getSTYLEABLE_VECTOR_DRAWABLE_WIDTH() {
        return STYLEABLE_VECTOR_DRAWABLE_WIDTH;
    }
}
